#!/usr/bin/env node
require('module-alias/register')
const debug = require('debug')('gcloudrig')
const { program } = require('commander');

// init
debug('init');
program.version('0.0.1');

// globals
program
  .name('gcloudrig')
  .option('--project <project>', 'The Google Cloud Platform project name to use.  (See https://cloud.google.com/sdk/gcloud/reference#--project)')

// define setup
program
  .command('setup')
  .option('--accelerator-type <accelerator-type>', 'The specific type of accelerator to attach to the instances.')
  .action(async () => {
    await require('@actions/setup').apply(null, arguments)
    debug('done')
  })

program.parse(process.argv)
debug(program.opts())